name: 'test call to yaml-update-action'
on:
  push:
    branches:
      - spike/test-action

jobs:
  test-update-file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cat Original yaml file
        run: cat sample_tests/tf_workspace.yaml
      - name: Update yaml file
        uses: ./
        with:
          valueFile: 'sample_tests/tf_workspace.yaml'
          propertyPath: 'spec.forProvider.planArgs[2]'
          value: "-var s3_object_version=v1.0.1-test"
          masterBranchName: main
          commitChange: 'false'
          updateFile: 'true'
      - name: Cat Updated yaml file
        run: cat sample_tests/tf_workspace.yaml

  test-update-file-2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cat Original yaml file
        run: |
          cat sample_tests/tf_workspace.yaml
          cat sample_tests/wbsds_app_kustomization.yaml
      - name: Update workspace yaml file
        uses: ./
        with:
          valueFile: 'sample_tests/tf_workspace.yaml'
          masterBranchName: main
          commitChange: 'false'
          updateFile: 'true'
          changes: |
            {
              "spec.forProvider.planArgs[2]": "-var semantic-version=v1.0.1-test",
              "spec.forProvider.applyArgs[2]": "-var semantic-version=v1.0.1-test",
              "spec.forProvider.destroyArgs[2]": "-var semantic-version=v1.0.1-test"
            }
      - name: Update kustomization yaml file
        uses: ./
        with:
          valueFile: 'sample_tests/wbsds_app_kustomization.yaml'
          masterBranchName: main
          commitChange: 'false'
          updateFile: 'true'
          changes: |
            {
              "images[0].newTag": "xyz123",
              "images[1].newTag": "abc456"
            }
      - name: Cat Updated yaml file
        run: |
          cat sample_tests/tf_workspace.yaml
          cat sample_tests/wbsds_app_kustomization.yaml
  
  test-multiple-file-changes-custom:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cat Original yaml file
        run: |
          cat sample_tests/tf_workspace.yaml
          cat sample_tests/wbsds_app_kustomization.yaml
      - uses: ./
        with:
          masterBranchName: main
          commitChange: 'false'
          updateFile: 'true'
          changes: |
            {
              "sample_tests/tf_workspace.yaml": {
                "spec.forProvider.planArgs[2]": "-var semantic-version=v1.0.1-test",
                "spec.forProvider.applyArgs[2]": "-var semantic-version=v1.0.1-test",
                "spec.forProvider.destroyArgs[2]": "-var semantic-version=v1.0.1-test"
              },
              "sample_tests/wbsds_app_kustomization.yaml": {
                "images[0].newTag": "xyz123",
                "images[1].newTag": "abc456"
              }
            }
      - name: Cat Updated yaml file
        run: |
          cat sample_tests/tf_workspace.yaml
          cat sample_tests/wbsds_app_kustomization.yaml

  test-update-file-wildcard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cat Original yaml file
        run: cat sample_tests/tf_workspace.yaml
      - name: Update yaml file
        uses: ./
        with:
          valueFile: 'sample_tests/tf_workspace.yaml'
          propertyPath: 'spec.forProvider[*][?(@.match(/s3_object_version/))]'
          value: "-var semantic_version=v1.0.1-test"
          masterBranchName: main
          commitChange: 'false'
          updateFile: 'true'
      - name: Cat Updated yaml file
        run: cat sample_tests/tf_workspace.yaml

  test-update-file-wildcard-2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cat Original yaml file
        run: cat sample_tests/tf_workspace.yaml
      - name: Update yaml file
        uses: ./
        with:
          valueFile: 'sample_tests/tf_workspace.yaml'
          masterBranchName: main
          commitChange: 'false'
          updateFile: 'true'
          changes: |
            {
              "spec.forProvider.planArgs[?(@.match(/s3_object_version/))]": "-var semantic_version=v1.0.1-test",
              "spec.forProvider.applyArgs[?(@.match(/s3_object_version/))]": "-var semantic_version=v1.0.1-test",
              "spec.forProvider.destroyArgs[?(@.match(/s3_object_version/))]": "-var semantic_version=v1.0.1-test"
            }
      - name: Cat Updated yaml file
        run: cat sample_tests/tf_workspace.yaml

  test-update-file-wildcard-3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cat Original yaml file
        run: cat sample_tests/wbsds_app_kustomization.yaml
      - name: Update yaml file
        uses: ./
        with:
          valueFile: 'sample_tests/wbsds_app_kustomization.yaml'
          masterBranchName: main
          commitChange: 'false'
          updateFile: 'true'
          changes: |
            {
              "images[?(@.name.match(/wbsds-application-frontend/))].newName": "geosigns-si-docker.artifactory.geosigns.shell.com/wbsds-application-frontend",
              "images[?(@.name.match(/wbsds-application-frontend/))].newTag": "xyz123",
              "images[?(@.name.match(/wbsds-application-backend/))].newName": "geosigns-si-docker.artifactory.geosigns.shell.com/wbsds-application-backend",
              "images[?(@.name.match(/wbsds-application-backend/))].newTag": "abc456"
            }
      - name: Cat Updated yaml file
        run: cat sample_tests/wbsds_app_kustomization.yaml

  tf-workspace2-test-multiple-file-changes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cat Original yaml file
        run: |
          cat sample_tests/tf_workspace_2.yaml
          cat sample_tests/wbsds_app_kustomization.yaml
      - uses: ./
        with:
          masterBranchName: main
          commitChange: 'false'
          updateFile: 'true'
          changes: |
            {
              "sample_tests/tf_workspace_2.yaml": {
                "spec.forProvider.vars[?(@.key == 'semantic_version')].value": "v1.0.1-test"
              },
              "sample_tests/wbsds_app_kustomization.yaml": {
                "images[0].newTag": "xyz123",
                "images[1].newTag": "abc456"
              }
            }
      - name: Cat Updated yaml file
        run: |
          cat sample_tests/tf_workspace_2.yaml
          cat sample_tests/wbsds_app_kustomization.yaml

  # "spec.forProvider[*][?(@.match(/s3_object_version/))]": "-var semantic_version=v1.0.1-test"
  test-multiple-file-changes-wildcard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cat Original yaml file
        run: |
          cat sample_tests/tf_workspace.yaml
          cat sample_tests/wbsds_app_kustomization.yaml
      - uses: ./
        with:
          masterBranchName: main
          commitChange: 'false'
          updateFile: 'true'
          changes: |
            {
              "sample_tests/tf_workspace.yaml": {
                "spec.forProvider.planArgs[?(@.match(/s3_object_version/))]": "-var semantic_version=v1.0.1-test",
                "spec.forProvider.applyArgs[?(@.match(/s3_object_version/))]": "-var semantic_version=v1.0.1-test",
                "spec.forProvider.destroyArgs[?(@.match(/s3_object_version/))]": "-var semantic_version=v1.0.1-test"
              },
              "sample_tests/wbsds_app_kustomization.yaml": {
                "images[?(@.name.match(/wbsds-application-frontend/))].newName": "geosigns-si-docker.artifactory.geosigns.shell.com/wbsds-application-frontend",
                "images[?(@.name.match(/wbsds-application-frontend/))].newTag": "xyz123",
                "images[?(@.name.match(/wbsds-application-backend/))].newName": "geosigns-si-docker.artifactory.geosigns.shell.com/wbsds-application-backend",
                "images[?(@.name.match(/wbsds-application-backend/))].newTag": "abc456"
              }
            }
      - name: Cat Updated yaml file
        run: |
          cat sample_tests/tf_workspace.yaml
          cat sample_tests/wbsds_app_kustomization.yaml

#  cleanup:
#    runs-on: ubuntu-latest
#    needs:
#      - test-target-repository
#      - test-update-file
#      - test-multiple-file-changes
#      - test-value-types
#    steps:
#      - uses: actions/checkout@v3
#      - name: Delete test branches
#        uses: dawidd6/action-delete-branch@v3
#        with:
#          token: ${{ secrets.GH_TOKEN }}
#          branches: deployment/v1.2.1,deployment/v1.0.1,deployment/test-bool-value,deployment/test-int-value,deployment/test-multi-file-update
